### ISSUE TITLE
Integration issues

### ISSUE THREAD

**Issue by cschol** [gwygonik/WygoniumModules#1]
A few issues that are observed during integration in the Rack library:

- Please don't put your plugin code in a subdirectory within the repository. The code needs to be at the root level of the repository for easy cloning and building on the Rack build system
- Your repository contains binaries (the `dist` directory). Please remove the any binaries from the repository.
- Your manifest contains invalid URLs:
```
[ORBsqVi] Validating plugin.json...
Exception validating URL: https://github.com/gwygonik/artificialcolors-vcv/Orbweaver (HTTP Error 404: Not Found)

Exception validating URL: https://github.com/gwygonik/artificialcolors-vcv/Orbweaver (HTTP Error 404: Not Found)

Exception validating URL: https://github.com/gwygonik/artificialcolors-vcv/Orbweaver (HTTP Error 404: Not Found)
FAILED
[ORBsqVi] Issues found in `plugin.json`:

Invalid URL: https://github.com/gwygonik/artificialcolors-vcv/Orbweaver
Invalid URL: https://github.com/gwygonik/artificialcolors-vcv/Orbweaver
Invalid URL: https://github.com/gwygonik/artificialcolors-vcv/Orbweaver
```

I recommend you recreate your repository in the correct layout and without binaries. Thank you!

**Comment by gwygonik** [comment]
Fixing. Thanks!
